#!/bin/bash
#
# This script configures the start information for this server.
# It's based on the default start script provided by aem, 
# located in crx-quickstart/bin but it has been slightly modified
# to keep the java process running in foreground, so we can launch it
# in a Docker container

# TCP port used for stop and status scripts
if [ -z "$CQ_PORT" ]; then
	echo "CQ_PORT environment varaible not set"
	exit 1
fi

# hostname of the interface that this server should listen to
#if [ -z "$CQ_HOST" ]; then
#	CQ_HOST=
#fi

# runmode(s)
if [ -z "$CQ_RUNMODE" ]; then
	echo "CQ_RUNMODE environment varaible not set"
	exit 1
fi

# name of the jarfile
#if [ -z "$CQ_JARFILE" ]; then
#	CQ_JARFILE=''
#fi

# use jaas.config
#if [ -z "$CQ_USE_JAAS" ]; then
#	CQ_USE_JAAS='true'
#fi

# config for jaas
if [ -z "$CQ_JAAS_CONFIG" ]; then
	CQ_JAAS_CONFIG='etc/jaas.config'
fi

# default JVM options
if [ -z "$CQ_JVM_OPTS" ]; then
	CQ_JVM_OPTS='-server -Xmx1024m -XX:MaxPermSize=256M -Djava.awt.headless=true'
fi

# file size limit (ulimit)
if [ -z "$CQ_FILE_SIZE_LIMIT" ]; then
	CQ_FILE_SIZE_LIMIT=8192
fi

if [ -z "$CQ_HOME" ]; then
	echo "CQ_HOME environment varaible not set"
	exit 1
fi

# ------------------------------------------------------------------------------
# do not configure below this point
# ------------------------------------------------------------------------------

if [ $CQ_FILE_SIZE_LIMIT ]; then
	CURRENT_ULIMIT=`ulimit`
	if [ $CURRENT_ULIMIT != "unlimited" ]; then
		if [ $CURRENT_ULIMIT -lt $CQ_FILE_SIZE_LIMIT ]; then
			echo "ulimit ${CURRENT_ULIMIT} is too small (must be at least ${CQ_FILE_SIZE_LIMIT})"
			exit 1
		fi
	fi
fi

cd $CQ_HOME/crx-quickstart
if [ -z $CQ_JARFILE ]; then
	CQ_JARFILE=`ls app/*.jar | head -1`
fi
CURR_DIR=$(basename $(pwd))
cd ..
START_OPTS="start -c ${CURR_DIR} -i launchpad"
if [ $CQ_PORT ]; then
	START_OPTS="${START_OPTS} -p ${CQ_PORT}"
fi
if [ $CQ_RUNMODE ]; then
	CQ_JVM_OPTS="${CQ_JVM_OPTS} -Dsling.run.modes=${CQ_RUNMODE}"
fi
if [ $CQ_HOST ]; then
	CQ_JVM_OPTS="${CQ_JVM_OPTS} -Dorg.apache.felix.http.host=${CQ_HOST}"
    START_OPTS="${START_OPTS} -a ${CQ_HOST}"
fi
if [ $CQ_USE_JAAS ]; then
    CQ_JVM_OPTS="${CQ_JVM_OPTS} -Djava.security.auth.login.config=${CQ_JAAS_CONFIG}"
fi
START_OPTS="${START_OPTS} -Dsling.properties=conf/sling.properties"

java $CQ_JVM_OPTS -jar $CURR_DIR/$CQ_JARFILE $START_OPTS